library:
  source-dirs: src
copyright: 2019 Luminiscental
maintainer: luminiscental01@gmail.com
dependencies:
- text
- base >= 4.7 && < 5
- containers
- mtl
- vty
- lens
- directory
name: hedit
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Luminiscental
github: Luminiscental/hedit
license: BSD3
executables:
  hedit-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hedit
description: Please see the README on GitHub at <https://github.com/Luminiscental/hedit#readme>
